services:
  - type: web
    name: my-personal-website
    env: node
    buildCommand: npm install && npm run build:ssr
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
